services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: cdm-backend-main
    env_file: .env
    ports:
      - "8000:8000"
    #    expose:
    #      - "8000"
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/app
      - ./migrations:/app/migrations
      - ./hf_cache:/root/.cache/huggingface
    restart: always
    depends_on:
      postgres_db:
        condition: service_healthy
      qdrant:
        condition: service_started
      ollama:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    container_name: cdm-frontend-main
    env_file: .env
    environment:
      - PYTHONPATH=.
    volumes:
      - ./src/frontend:/app/src/frontend
    restart: always
    depends_on:
      backend:
        condition: service_started


  qdrant:
    image: qdrant/qdrant
    container_name: cdm-qdrant-main
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
  postgres_db:
    container_name: cdm-postgres-main
    image: postgres
    env_file: .env
    expose:
      - "5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: cdm-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
