"""add score

Revision ID: ae764eaed805
Revises: dd54ac811ef5
Create Date: 2026-05-18 11:23:24.906836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae764eaed805'
down_revision: Union[str, Sequence[str], None] = 'dd54ac811ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog_history', sa.Column('score', sa.Float(), nullable=True, comment='Уверенность ответа при ранжировании (max)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialog_history', 'score')
    # ### end Alembic commands ###
