"""+know_base, +history dialog base

Revision ID: dd54ac811ef5
Revises: 
Create Date: 2026-05-17 14:44:53.874650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd54ac811ef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('dialog_type', sa.String(length=64), nullable=True),
    sa.Column('operator', sa.Boolean(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialog_history_user_id'), 'dialog_history', ['user_id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True, comment='дополнительная информация о документе'),
    sa.Column('finished_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_index(op.f('ix_knowledge_base_title'), 'knowledge_base', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_title'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_dialog_history_user_id'), table_name='dialog_history')
    op.drop_table('dialog_history')
    # ### end Alembic commands ###
